### ISSUE TITLE
output of network yolo_0 and yolo_1

### ISSUE THREAD

**Issue by giandras033235** [Yu-Zhewen/Tiny_YOLO_v3_ZYNQ#11]
hi,

As you stated in the paper the output of the yolo network should be 13*13*255, but your output yolo_0.out is 13*13*256, what is the reason for the difference?
My goal would be to generate bounding boxes to the outputs, I can already generate bboxes to  a network output like 13*13*255 as it is dividable by 85. Could you give any hint, what am I missing with your outputs?
Thanks in advance.

**Comment by Yu-Zhewen** [comment]
The number of channels is padded to multiples of 4, so there is an extra channel filled with zeros

**Comment by giandras033235** [comment]
Thanks for the quick answer, does this mean, relating to your section channel interleaving, that an input looks like the following: R G B 0 R G B 0?

**Comment by giandras033235** [comment]
Another question of mine would be that if I take a look at the output, I cannot recognize the pattern of a standard yolo output (1x85 vector) but it looks like as it would be a 1x32 vector, what is the reason for it? You wrote that the COCO dataset has 80 classes, so I cannot see why it does not have the same form. Also what is the reason, that in the yolo_0.out most of the numbers are not zeros (class scores)?

**Comment by Yu-Zhewen** [comment]
You are right that channels are interleaved in a group 32. There are two constraints here: 
(1) the number of channels that can be sent to the IP at the same time, which is 4, because each port of DMA has 64 bits at maximum and the wordlength is 16; 
(2) the number of channels that the IP can buffer, which is 32(https://github.com/Yu-Zhewen/Tiny_YOLO_v3_ZYNQ/blob/d3d83d50a34378933b05b962c956e71654b390d8/code/hls/yolo_conv/src/yolo_conv.h#L15)

I am not sure what you mean that class scores are not zeros, as they be any value between 0 to 1 because of the sigmoid in yolo layer.
